### ISSUE TITLE
Worked on localhost xampp server, but not on website server

### ISSUE THREAD

**Issue by jamminjames** [thomthom/php-resumable-download-server#9]
I had this working well on my localhost xampp server, but when I moved it to our site,  it didn't quite right. I think I have all the settings correct, and it finds the files in the directory outside the website alright, which we have set up for pdf files, but when you click on the link, instead of doing the query string, it just tries to  find the file at the website root.

The site is on an nginx server, so the  .htaccess file won't work, could that be the problem? I tried doing a redirect for nginx, but nothing changed. Not sure if the redirects I tried were the problem, or what. 

Any suggestions on configuring the redirect for nginx? 

For the .htaccess redirect on my localhost, I changed the suggested one to this, which works better, because the suggested one stopped the file list from showing correctly. This one looks for any .pdf request on the root:

```
Options +FollowSymlinks
RewriteEngine on
RewriteCond %{REQUEST_URI} (.*).pdf
RewriteRule ^(.+)$ index-download.php?file=$1
```

So, to convert, I tried this for nginx, and I know I put it in the proper place in the nginx configuration files. But clicking on the file links kept going to the root looking for the pdf file, instead of doing the query string:

```
  if ($request_uri ~ "(.*).pdf"){
    rewrite ^(.+)$ /index-download.php?file=$1;
  }
```

**Comment by thomthom** [comment]
Yes, `.htaccess` won't work on nginx. I'm afraid that I'm not that familiar with nginx myself though. I have been (slowly) refactoring my site to be able to be deployed on nginx instead of apache.

Looking at that migration project it looks like I have tried to convert the `.htaccess` to nginx as:

```
location / {
  rewrite ^(.+)$ /index.php?file=$1;
  # try_files $uri $uri/ /index.php?$query_string;

  # TODO:
  # AddType application/x-windows-gadget gadget
  # RewriteCond %{HTTP_USER_AGENT} ".* MSIE .*"
  # RewriteRule ^(.*)\.(gadget)$ - [L,T=application/x-windows-gadget]
}

location = / {
  try_files $uri $uri/ /index.php?$query_string;
}
```

Since I'm not experienced in nginx I don't know if this is fully correct, but seems to do the trick.

**Comment by jamminjames** [comment]
Okay, thanks. Will let you know if it works for me.

**Comment by jamminjames** [comment]
I made a change to avoid needing a redirect altogether. Do you think any harm to the intended function of your script will be caused by it?

In index.php, changed line 425 from:

`$files[] = "<tr><td>$icon</td><td><a href=\"$path\">$file</a></td><td>$type</td><td>$size</td></tr>\n";`

to:

`$files[] = "<tr><td>$icon</td><td><a href='index.php?file=$file'>$file</a></td><td>$type</td><td>$size</td></tr>\n"; `

So now, when clicking on a file name, it goes to `index.php?file=$file`, thus no longer needing the redirect. Your script already changes that filename to include the actual location of the file outside of the website, so why not just use the url query in the href, instead of redirecting to it?

**Comment by thomthom** [comment]
That should work fine. The redirect is mainly for "pretty" URLs.

**Comment by jamminjames** [comment]
Great, thanks!
